### GENERAL LIBRARY IMPORTS

In [1190]:
import pandas as pd
import numpy as np

### DATASET CLEANING

made a copy of the original dataset, handled missing values

- renamed some of the columns
- dropped the dates column
- updating the 'time of accidents' column from 12h to 24h clock system
- modifying the accident victims column as per the death casuality count (total people confirmed dead)
- upgraded the weather conditions column; include as a factor to the prediciton

In [1191]:
df_orig = pd.read_csv("data/traffic_data.csv")
df_orig.head()

,Date,Accident Spot,Area,County,Road/ Highway,Brief Accident Details/Cause,Victims,Total people confirmed dead,Time of the Accidents,Weather conditions
0,8/8/2023,Sobea,Sobea,Nakuru,Nakuru-Eldoret Highway,Head on Collision,Passengers,4,4.30 pm,NaN
1,8/7/2023,Maai-Mahiu,Naivasha,Nakuru,Maai-Mahiu Naivasha Highway,vehicle and motorcycle collision,Passengers,1,5.50 pm,NaN
2,7/25/2023,Ntulele,Ntulele,Narok,Narok Mai Mahiu road,Head on Collision,Drivers/Occupants,4,NaN,NaN
3,12/2/2022,Suswa,Suswa,Narok,Narok Mai Mahiu road,Head on Collision,Driver and passengers,3,6.00 pm,NaN
4,12/1/2022,Mutira,Mutira,Kirinyaga,Kerugoya-Karatina Road,Run over,Pedestrian,1,NaN,NaN

In [1192]:
df_orig = pd.read_csv("data/traffic_data_updated.csv")
df_orig.head()

,Date,Accident Spot,Area,County,Road/ Highway,Brief Accident Details/Cause,Victims,Total people confirmed dead,Time of the Accidents,Weather conditions
0,8/8/2023,Sobea,Sobea,Nakuru,Nakuru-Eldoret Highway,Head on Collision,Passengers,4,16:30,Windy
1,8/7/2023,Maai-Mahiu,Naivasha,Nakuru,Maai-Mahiu Naivasha Highway,Vehicle and motorcycle collision,Passenger,1,17:50,Cloudy
2,7/25/2023,Ntulele,Ntulele,Narok,Narok Mai Mahiu road,Head on Collision,"Driver, Passengers",4,01:30,Cloudy
3,12/2/2022,Suswa,Suswa,Narok,Narok Mai Mahiu road,Head on Collision,"Driver, Passengers",3,18:00,Windy
4,12/1/2022,Mutira,Mutira,Kirinyaga,Kerugoya-Karatina Road,Run over,Pedestrian,1,12:26,Sunny

In [1193]:
df = df_orig.copy()
df.head()

,Date,Accident Spot,Area,County,Road/ Highway,Brief Accident Details/Cause,Victims,Total people confirmed dead,Time of the Accidents,Weather conditions
0,8/8/2023,Sobea,Sobea,Nakuru,Nakuru-Eldoret Highway,Head on Collision,Passengers,4,16:30,Windy
1,8/7/2023,Maai-Mahiu,Naivasha,Nakuru,Maai-Mahiu Naivasha Highway,Vehicle and motorcycle collision,Passenger,1,17:50,Cloudy
2,7/25/2023,Ntulele,Ntulele,Narok,Narok Mai Mahiu road,Head on Collision,"Driver, Passengers",4,01:30,Cloudy
3,12/2/2022,Suswa,Suswa,Narok,Narok Mai Mahiu road,Head on Collision,"Driver, Passengers",3,18:00,Windy
4,12/1/2022,Mutira,Mutira,Kirinyaga,Kerugoya-Karatina Road,Run over,Pedestrian,1,12:26,Sunny

In [1194]:
df = df.rename(
    columns={
        'Brief Accident Details/Cause': 'Accident Briefing',
        'Total people confirmed dead': 'Dead Casualties Count',
        'Weather conditions': 'Weather'
    }
)
df.columns

Index(['Date', 'Accident Spot', 'Area', 'County', 'Road/ Highway',
       'Accident Briefing', 'Victims', 'Dead Casualties Count',
       'Time of the Accidents', 'Weather'],
      dtype='object')

In [1195]:
df.head()

,Date,Accident Spot,Area,County,Road/ Highway,Accident Briefing,Victims,Dead Casualties Count,Time of the Accidents,Weather
0,8/8/2023,Sobea,Sobea,Nakuru,Nakuru-Eldoret Highway,Head on Collision,Passengers,4,16:30,Windy
1,8/7/2023,Maai-Mahiu,Naivasha,Nakuru,Maai-Mahiu Naivasha Highway,Vehicle and motorcycle collision,Passenger,1,17:50,Cloudy
2,7/25/2023,Ntulele,Ntulele,Narok,Narok Mai Mahiu road,Head on Collision,"Driver, Passengers",4,01:30,Cloudy
3,12/2/2022,Suswa,Suswa,Narok,Narok Mai Mahiu road,Head on Collision,"Driver, Passengers",3,18:00,Windy
4,12/1/2022,Mutira,Mutira,Kirinyaga,Kerugoya-Karatina Road,Run over,Pedestrian,1,12:26,Sunny

In [1196]:
# check for any missing values in the dataset
df.isna().sum()

Date                      0
Accident Spot             0
Area                      0
County                    0
Road/ Highway             0
Accident Briefing         0
Victims                  13
Dead Casualties Count     0
Time of the Accidents     0
Weather                   0
dtype: int64

In [1197]:
# fill the victim column with average value
frequent = df['Victims'].mode()[0]
df['Victims'] = df['Victims'].fillna(frequent)

In [1198]:
# check for any missing values in the dataset
df.isna().sum()

Date                     0
Accident Spot            0
Area                     0
County                   0
Road/ Highway            0
Accident Briefing        0
Victims                  0
Dead Casualties Count    0
Time of the Accidents    0
Weather                  0
dtype: int64

In [1199]:
# Drop the date column
df = df.drop("Date", axis=1)

In [1200]:
# Drop the weather column
df = df.drop("Weather", axis=1)

In [1201]:
df.columns

Index(['Accident Spot', 'Area', 'County', 'Road/ Highway', 'Accident Briefing',
       'Victims', 'Dead Casualties Count', 'Time of the Accidents'],
      dtype='object')

In [1202]:
df.head()

,Accident Spot,Area,County,Road/ Highway,Accident Briefing,Victims,Dead Casualties Count,Time of the Accidents
0,Sobea,Sobea,Nakuru,Nakuru-Eldoret Highway,Head on Collision,Passengers,4,16:30
1,Maai-Mahiu,Naivasha,Nakuru,Maai-Mahiu Naivasha Highway,Vehicle and motorcycle collision,Passenger,1,17:50
2,Ntulele,Ntulele,Narok,Narok Mai Mahiu road,Head on Collision,"Driver, Passengers",4,01:30
3,Suswa,Suswa,Narok,Narok Mai Mahiu road,Head on Collision,"Driver, Passengers",3,18:00
4,Mutira,Mutira,Kirinyaga,Kerugoya-Karatina Road,Run over,Pedestrian,1,12:26

### ACCIDENT PREDICTION

where is the most dangerous spot to travel to

- based on most dangerous and least dangerous location -- location risk prediction
- using the area, accident spot columns for averaging the dangerous places rather than counties

In [1203]:
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, roc_curve, auc

In [1204]:
def get_models():
    models = {
        'Logistic Regression': LogisticRegression(solver='lbfgs', C=10),
        'Decision Tree': DecisionTreeClassifier(criterion='entropy', max_depth=10, min_samples_split=5),
        'Random Forest': RandomForestClassifier(n_estimators=100, max_depth=None),
        'KNN': KNeighborsClassifier(n_neighbors=5, weights="uniform", metric="euclidean")
    }
    return models

#### PREDICTING MOST/LEAST DANGEROUS COUNTIES (LOCATION RISK)

- calculated the average victim deaths per accident spot.
- a death casualty threshold so that i can categorize into low and high
- create the feature targets and split the data into training and test datasets
-

In [1205]:
def calculate_location_risk():
    # calculate average deaths per area
    area_avg_deaths = df.groupby('Accident Spot')[
        'Dead Casualties Count'].mean()
    death_thresholds = area_avg_deaths.quantile([0.22, 0.78])

    df['Location Risk'] = df['Accident Spot'].map(
        lambda x: 'Low' if area_avg_deaths[x] <= death_thresholds.iloc[0]
        else 'High'
    )
    return df


calculate_location_risk()

,Accident Spot,Area,County,Road/ Highway,Accident Briefing,Victims,Dead Casualties Count,Time of the Accidents,Location Risk
0,Sobea,Sobea,Nakuru,Nakuru-Eldoret Highway,Head on Collision,Passengers,4,16:30,High
1,Maai-Mahiu,Naivasha,Nakuru,Maai-Mahiu Naivasha Highway,Vehicle and motorcycle collision,Passenger,1,17:50,Low
2,Ntulele,Ntulele,Narok,Narok Mai Mahiu road,Head on Collision,"Driver, Passengers",4,01:30,High
3,Suswa,Suswa,Narok,Narok Mai Mahiu road,Head on Collision,"Driver, Passengers",3,18:00,High
4,Mutira,Mutira,Kirinyaga,Kerugoya-Karatina Road,Run over,Pedestrian,1,12:26,Low
...,...,...,...,...,...,...,...,...,...
76,Losengeli,Sabatia,Vihiga,Nairobi Kakamega road,Bus lost control and rolled over,Passenger,1,03:45,Low
77,Isinya,Isinya,Kajiado,Namanga Road,Car rammed into a trailer,Passengers,1,23:00,High
78,Kinugi,Kinugi,Nakuru,Naivasha Nairobi Highway,Truck driver collided with an oncoming matatu,Passenger,1,06:36,High
79,Kinugi,Kinugi,Nakuru,Nakuru - Nairobi highway,Car rammed into a lorry,Passengers,4,22:35,High
80,Sobea,Sobea,Nakuru,Nakuru Eldoret Highway,matatu collided with a truck,Passengers,2,04:30,High

In [1206]:
def create_feature_target(df):
    features = [
        'Accident Spot',
        'Area',
    ]

    X = df[features]
    y_deaths = pd.cut(
        df['Dead Casualties Count'],
        bins=[1, 3, np.inf],
        labels=['Low', 'High']
    )

    y_location = df['Location Risk']
    return X, y_deaths, y_location


X, y_deaths, y_location = create_feature_target(df)
df.head()

,Accident Spot,Area,County,Road/ Highway,Accident Briefing,Victims,Dead Casualties Count,Time of the Accidents,Location Risk
0,Sobea,Sobea,Nakuru,Nakuru-Eldoret Highway,Head on Collision,Passengers,4,16:30,High
1,Maai-Mahiu,Naivasha,Nakuru,Maai-Mahiu Naivasha Highway,Vehicle and motorcycle collision,Passenger,1,17:50,Low
2,Ntulele,Ntulele,Narok,Narok Mai Mahiu road,Head on Collision,"Driver, Passengers",4,01:30,High
3,Suswa,Suswa,Narok,Narok Mai Mahiu road,Head on Collision,"Driver, Passengers",3,18:00,High
4,Mutira,Mutira,Kirinyaga,Kerugoya-Karatina Road,Run over,Pedestrian,1,12:26,Low

In [1207]:
def create_preprocessor():
    categorical_features = ['Accident Spot', 'Area']

    categorical_transformer = OneHotEncoder(handle_unknown='ignore')

    preprocessor = ColumnTransformer(
        transformers=[
            ('cat', categorical_transformer, categorical_features)
        ]
    )
    return preprocessor


def split_data(X, y, test_size=0.35, random_state=45):
    return train_test_split(X, y, test_size=test_size, random_state=random_state)

# model training and evaluation


def train_evaluate_models(X, y, preprocessor):
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.35, random_state=45)
    models = get_models()
    results = {}

    for name, model in models.items():
        pipeline = Pipeline([
            ('preprocessor', preprocessor),
            ('classifier', model)
        ])

        pipeline.fit(X_train, y_train)
        y_pred = pipeline.predict(X_test)
        accuracy = accuracy_score(y_test, y_pred)
        results[name] = accuracy
        print(f"{name} - Accuracy: {accuracy:.3f}")
        print(classification_report(y_test, y_pred, zero_division=1.0))
        print("-----------------------------")

    return results


def main():
    preprocessor = create_preprocessor()
    print("\nTraining models for Location Risk Prediction:")
    results_location = train_evaluate_models(X, y_location, preprocessor)


if __name__ == '__main__':
    main()

Training models for Location Risk Prediction:
Logistic Regression - Accuracy: 0.828
              precision    recall  f1-score   support

        High       0.81      1.00      0.90        22
         Low       1.00      0.29      0.44         7

    accuracy                           0.83        29
   macro avg       0.91      0.64      0.67        29
weighted avg       0.86      0.83      0.79        29

-----------------------------
Decision Tree - Accuracy: 0.828
              precision    recall  f1-score   support

        High       0.81      1.00      0.90        22
         Low       1.00      0.29      0.44         7

    accuracy                           0.83        29
   macro avg       0.91      0.64      0.67        29
weighted avg       0.86      0.83      0.79        29

-----------------------------
Random Forest - Accuracy: 0.793
              precision    recall  f1-score   support

        High       0.79      1.00      0.88        22
         Low       1.00      0.14      0.25         7

    accuracy                           0.79        29
   macro avg       0.89      0.57      0.56        29
weighted avg       0.84      0.79      0.73        29

-----------------------------
KNN - Accuracy: 0.759
              precision    recall  f1-score   support

        High       0.76      1.00      0.86        22
         Low       1.00      0.00      0.00         7

    accuracy                           0.76        29
   macro avg       0.88      0.50      0.43        29
weighted avg       0.82      0.76      0.65        29

-----------------------------

In [1208]:
# import matplotlib.pyplot as plt
# import seaborn as sns


def plot_confusion_matrix(y_true, y_pred, model_name):
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(6, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=[
                'Low', 'Medium', 'High'], yticklabels=['Low', 'Medium', 'High'])
    plt.title(f'Confusion Matrix for {model_name}')
    plt.xlabel('Predicted Label')
    plt.ylabel('True Label')
    plt.show()


plot_confusion_matrix(y_true, y_pred, model_name)


def plot_roc_curve(y_test, y_probs, model_name):
    fpr, tpr, _ = roc_curve(y_test, y_probs, pos_label='High')
    roc_auc = auc(fpr, tpr)
    plt.figure(figsize=(8, 6))
    plt.plot(fpr, tpr, color='blue', lw=2,
             label=f'ROC curve (area = {roc_auc:.2f})')
    plt.plot([0, 1], [0, 1], color='gray', linestyle='--')
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title(f'ROC Curve for {model_name}')
    # plt.legend(loc="\lower right\")
    plt.show()


plot_roc_curve(y_test, y_probs, model_name)

NameError: name 'y_true' is not defined